image: Visual Studio 2015

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: CodecovProject.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Tests\Rovecode.Lotos.Tests\bin\Debug\Rovecode.Lotos.Tests.dll -noshadow" -filter:"+[Rovecode.Lotos*]* -[Rovecode.Lotos.Tests*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml"
