name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Nuget
      uses: NuGet/setup-nuget@v1.0.5
      with:
          nuget-api-key: oy2hwwfgfeqz3zwa7mdqnbr3usb3ksbedjqegogbw7hwfu
          nuget-api-key-source: Rovecode.Lotos
